import streamlit as st
from audiorecorder import audiorecorder
import whisper
import pickle
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import re
import pandas as pd
from io import BytesIO
import os

# Define the labeled examples
examples = [('we are actively seeking talented individuals to join our growing startup',
  'Talent'),
 ('our startup is looking for exceptional talent with a strong background in software engineering ',
  'Talent'),
 ('we value creativity and innovation and we are eager to attract talented individuals who can contribute to our team ',
  'Talent'),
 ('as a startup we prioritize hiring top talent who can adapt quickly to a fast paced environment ',
  'Talent'),
 ('our company believes in nurturing talent and providing opportunities for growth within the organization ',
  'Talent'),
 ('we are seeking talented individuals who possess a passion for problem solving and can bring fresh perspectives to our startup ',
  'Talent'),
 ('if you have a track record of success and are eager to work in a dynamic startup environment we want to hear from you ',
  'Talent'),
 ('join our team of talented professionals who are dedicated to pushing the boundaries of technology in the startup landscape ',
  'Talent'),
 ('we have high standards when it comes to talent acquisition and look for candidates who demonstrate exceptional skills and potential ',
  'Talent'),
 ('at our startup we believe that diversity and inclusion are crucial in attracting top talent and fostering a thriving work culture ',
  'Talent'),
 ('we are actively seeking talented individuals to join our growing startup ',
  'Talent'),
 ('our startup is expanding and we re on the lookout for talented individuals who can help drive our growth and success ',
  'Talent'),
 ('if you re a talented go getter with a passion for innovation we want you on our team ',
  'Talent'),
 ('we re actively recruiting top tier talent to join our dynamic startup and be part of our journey towards success ',
  'Talent'),
 ('calling all talented individuals join our rapidly growing startup and make your mark in the industry ',
  'Talent'),
 ('we believe that talented people are the backbone of any successful startup join us and be part of our success story ',
  'Talent'),
 ('if you re a talented problem solver with a hunger for challenges we have an exciting role waiting for you in our startup ',
  'Talent'),
 ('we re building a team of talented individuals who share our vision and are ready to make a significant impact in the market ',
  'Talent'),
 ('do you have what it takes to be a part of a fast paced startup environment we re seeking talented individuals like you ',
  'Talent'),
 ('our startup is on a mission to revolutionize the industry and we need talented professionals to help us achieve our goals ',
  'Talent'),
 ('if you re a talented self starter who thrives in a collaborative environment we want to hear from you ',
  'Talent'),
 ('we re looking for talented individuals who are passionate about our product and eager to contribute to its success ',
  'Talent'),
 ('join our team of talented innovators and work on cutting edge projects that will shape the future of our startup ',
  'Talent'),
 ('talented minds wanted be part of our startup s success by bringing your unique skills and ideas to the table ',
  'Talent'),
 ('are you a talented leader ready to take on new challenges join us as we grow and build a remarkable startup together ',
  'Talent'),
 ('we re actively seeking talented individuals who can bring fresh perspectives and help us stay ahead in a competitive market ',
  'Talent'),
 ('if you re a talented communicator with a knack for building relationships join our startup and make an impact in our industry ',
  'Talent'),
 ('at our startup we value talent and offer a supportive environment where you can thrive and reach your full potential ',
  'Talent'),
 ('join our startup and work alongside a team of talented professionals who are passionate about making a difference ',
  'Talent'),
 ('we re looking for talented individuals who are eager to learn grow and contribute to the success of our startup ',
  'Talent'),
 ('if you have a talent for problem solving and a drive for innovation we want you to join our dynamic startup ',
  'Talent'),
 ('join our startup and be part of a team that values talent creativity and collaboration ',
  'Talent'),
 ('we re actively searching for talented individuals who can contribute their skills and expertise to fuel our startup s success ',
  'Talent'),
 ('are you a talented professional seeking a rewarding career in a fast paced startup environment look no further ',
  'Talent'),
 ('our startup is dedicated to attracting top talent and creating a culture of excellence and growth ',
  'Talent'),
 ('if you re a talented individual with a passion for entrepreneurship our startup provides the perfect platform for your success ',
  'Talent'),
 ('we believe that talent knows no boundaries and we welcome individuals from all backgrounds to join our startup ',
  'Talent'),
 ('our startup is on the lookout for talented problem solvers who can think outside the box and drive innovation ',
  'Talent'),
 ('join our team of talented visionaries and shape the future of our startup as we disrupt the industry ',
  'Talent'),
 ('we re seeking talented individuals who are not only skilled in their respective fields but also share our startup s values and vision ',
  'Talent'),
 ('at our startup we foster a culture of continuous learning and development to help our talented employees reach their full potential ',
  'Talent'),
 ('if you re a talented leader with a track record of success join our startup and help us build a thriving organization ',
  'Talent'),
 ('we recognize that attracting and retaining top talent is key to our startup s growth and are committed to creating an environment where talent can flourish ',
  'Talent'),
 ('join our startup and become part of a community where your talents are celebrated and your ideas are valued ',
  'Talent'),
 ('are you a talented multitasker with a passion for taking on new challenges join our startup and make a real impact ',
  'Talent'),
 ('we re seeking talented individuals who are not afraid to take risks challenge the status quo and drive our startup to new heights ',
  'Talent'),
 ('join our startup and work alongside a diverse team of talented individuals who inspire and support each other ',
  'Talent'),
 ('we believe in empowering our talented employees by providing them with the tools resources and opportunities they need to succeed ',
  'Talent'),
 ('our startup is committed to creating a work environment that encourages collaboration creativity and the nurturing of talent ',
  'Talent'),
 ('if you re a talented professional looking for a dynamic startup where you can make a meaningful impact we would love to hear from you ',
  'Talent'),
 ('we re actively searching for talented individuals who are passionate about our startup s mission and ready to make a difference ',
  'Talent'),
 ('join our startup and be part of a team where your talent is valued and your contributions have a direct impact on our success ',
  'Talent'),
 ('are you a talented problem solver with a keen eye for detail our startup is looking for individuals like you to join our ranks ',
  'Talent'),
 ('we re building a culture that celebrates diversity and fosters the growth of talented individuals from all backgrounds ',
  'Talent'),
 ('if you re a talented communicator with the ability to inspire and lead our startup offers an exciting leadership opportunity ',
  'Talent'),
 ('join our startup and work on cutting edge projects alongside a team of talented professionals who share your passion for innovation ',
  'Talent'),
 ('we re seeking talented individuals who can bring fresh ideas and perspectives to our startup and contribute to our ongoing success ',
  'Talent'),
 ('our startup believes in investing in talent development providing continuous learning opportunities for our dedicated employees ',
  'Talent'),
 ('are you a talented team player who thrives in a collaborative environment join our startup and make an impact through collective success ',
  'Talent'),
 ('we re actively recruiting talented individuals who have a growth mindset and are eager to take on new challenges in our startup ',
  'Talent'),
 ('join our startup and be part of a culture that celebrates and rewards the entrepreneurial spirit and the talents it brings ',
  'Talent'),
 ('we believe that our startup s success lies in attracting and retaining top talent and we re committed to creating an environment where talent can thrive ',
  'Talent'),
 ('if you re a talented visionary with a knack for spotting trends our startup provides the perfect platform for you to shape the future ',
  'Talent'),
 ('we re looking for talented individuals who are not afraid to push boundaries experiment and create new possibilities in our startup ',
  'Talent'),
 ('join our team of talented problem solvers and work on innovative solutions that address real world challenges in our industry ',
  'Talent'),
 ('at our startup we believe that every individual has unique talents to offer and we re dedicated to unlocking their full potential ',
  'Talent'),
 ('we re seeking talented professionals who are passionate about delivering exceptional user experiences and driving customer satisfaction ',
  'Talent'),
 ('join our startup and embark on a journey of personal and professional growth alongside a supportive community of talented individuals ',
  'Talent'),
 ('are you a talented data analyst with a passion for uncovering insights our startup is looking for individuals like you to join our analytics team ',
  'Talent'),
 ('we re on the lookout for talented individuals who thrive in a fast paced environment and are excited to contribute to our startup s rapid growth ',
  'Talent'),
 ('i m looking to hire talented software developers for my startup ',
  'Talent'),
 ('can venusventure connect me with experienced marketing professionals ',
  'Talent'),
 ('i need assistance in finding a skilled product designer for my startup ',
  'Talent'),
 ('are there any resources or programs to help me recruit top talent ',
  'Talent'),
 ('can venusventure help me build a diverse and inclusive team ', 'Talent'),
 ('i m seeking a co founder with expertise in business development ',
  'Talent'),
 ('how can i attract and retain high quality talent for my startup ',
  'Talent'),
 ('can venusventure recommend any recruitment agencies or platforms ',
  'Talent'),
 ('are there networking events where i can meet potential team members ',
  'Talent'),
 ('i need assistance in hiring executive level positions for my startup ',
  'Talent'),
 ('invest in our startup and become part of a groundbreaking venture poised for exceptional growth ',
  'Investment'),
 ('we re seeking strategic investors who share our vision and want to be part of the next big success story ',
  'Investment'),
 ('join our journey by investing in our startup and capitalize on the potential for substantial returns ',
  'Investment'),
 ('invest in our innovative startup and help us disrupt the industry with our groundbreaking solutions ',
  'Investment'),
 ('we re actively seeking investment partners who believe in our mission and want to be part of our exciting growth trajectory ',
  'Investment'),
 ('invest in our startup and be part of a lucrative opportunity that has the potential to reshape the market ',
  'Investment'),
 ('join our network of investors and gain access to a portfolio of high potential startups with exceptional growth prospects ',
  'Investment'),
 ('we re inviting investors to join us on our mission to revolutionize the industry and generate significant returns on investment ',
  'Investment'),
 ('invest in our startup and be at the forefront of innovation driving positive change and reaping the rewards ',
  'Investment'),
 ('we re looking for visionary investors who understand the potential of our startup and want to make a strategic investment ',
  'Investment'),
 ('join our investor community and gain exclusive access to exciting investment opportunities in the fast growing startup ecosystem ',
  'Investment'),
 ('invest in our startup and leverage the expertise of our seasoned team to maximize your return on investment ',
  'Investment'),
 ('we re seeking strategic investors who can provide more than just capital investors who can contribute valuable industry insights and networks ',
  'Investment'),
 ('join us in fueling the growth of our startup by making an impactful investment that will propel us to new heights ',
  'Investment'),
 ('invest in our startup and play a vital role in shaping the future of our industry through innovation and disruptive solutions ',
  'Investment'),
 ('we re seeking like minded investors who believe in the power of technology and want to be part of our startup s success story ',
  'Investment'),
 ('join our network of visionary investors and gain access to a pipeline of promising startups with high growth potential ',
  'Investment'),
 ('invest in our startup and diversify your portfolio with a high potential investment opportunity in a rapidly evolving market ',
  'Investment'),
 ('we re inviting investors to join us in building a sustainable future through impactful investments in our socially responsible startup ',
  'Investment'),
 ('invest in our startup and enjoy the excitement of being part of an entrepreneurial journey with limitless possibilities for success ',
  'Investment'),
 ('investments play a crucial role in fueling the growth and expansion of startups providing the necessary capital to fund operations development and scaling ',
  'Investment'),
 ('startups rely on investments to attract top talent build a skilled team and foster innovation through research and development ',
  'Investment'),
 ('investments provide startups with the financial resources needed to penetrate the market establish their brand and gain a competitive edge ',
  'Investment'),
 ('with the help of investments startups can invest in marketing and customer acquisition strategies to reach a wider audience and drive business growth ',
  'Investment'),
 ('investments enable startups to invest in technology infrastructure equipment and tools empowering them to operate efficiently and deliver high quality products or services ',
  'Investment'),
 ('startups can leverage investments to expand their product or service offerings diversify revenue streams and adapt to evolving market trends ',
  'Investment'),
 ('investments provide startups with the opportunity to attract experienced advisors and mentors who can provide valuable guidance and industry expertise ',
  'Investment'),
 ('with the support of investments startups can conduct market research gather insights and make data driven decisions to optimize their operations and offerings ',
  'Investment'),
 ('investments allow startups to forge strategic partnerships collaborations and acquisitions facilitating access to new markets customers and distribution channels ',
  'Investment'),
 ('startups can use investments to build a robust intellectual property portfolio protect their innovations and gain a competitive advantage in the market ',
  'Investment'),
 ('investments provide startups with the financial stability and runway needed to weather challenges overcome obstacles and sustain long term growth ',
  'Investment'),
 ('by securing investments startups can attract media attention enhance their brand visibility and establish credibility within their industry ',
  'Investment'),
 ('investments can provide startups with the resources to expand their physical infrastructure such as office spaces or manufacturing facilities to support their growth ',
  'Investment'),
 ('startups can leverage investments to implement scalable business models streamline operations and optimize processes for efficiency and profitability ',
  'Investment'),
 ('investments allow startups to attract partnerships and collaborations with established companies opening doors to shared resources expertise and market access ',
  'Investment'),
 ('with the help of investments startups can embark on research and development initiatives driving innovation and creating groundbreaking solutions ',
  'Investment'),
 ('investments enable startups to hire specialized talent build cross functional teams and foster a culture of creativity and entrepreneurship ',
  'Investment'),
 ('startups can use investments to develop and execute marketing strategies raise brand awareness and engage with their target audience ',
  'Investment'),
 ('investments provide startups with the flexibility to iterate and pivot their business models based on market feedback and changing customer needs ',
  'Investment'),
 ('by attracting investments startups gain the confidence of potential customers partners and stakeholders enhancing their reputation and market position ',
  'Investment'),
 ('investing in startups provides an opportunity to participate in the early stages of groundbreaking ideas and potentially achieve significant financial returns ',
  'Investment'),
 ('startups rely on investments to accelerate product development launch new features and stay ahead of competitors in a rapidly evolving market ',
  'Investment'),
 ('investments fuel the research and development efforts of startups enabling them to innovate and bring disruptive solutions to the market ',
  'Investment'),
 ('by investing in startups you become a key player in shaping the future and supporting the growth of the entrepreneurial ecosystem ',
  'Investment'),
 ('startups use investments to build a solid infrastructure implement scalable systems and establish a strong foundation for sustainable growth ',
  'Investment'),
 ('investments provide startups with the necessary runway to focus on customer acquisition market penetration and revenue generation ',
  'Investment'),
 ('investing in startups is an opportunity to support visionary founders passionate teams and their mission to solve real world problems ',
  'Investment'),
 ('startups rely on investments to attract strategic partners expand distribution networks and reach new markets globally ',
  'Investment'),
 ('investments enable startups to navigate challenges seize market opportunities and adapt their business strategies for long term success ',
  'Investment'),
 ('investing in startups allows you to be part of the entrepreneurial journey experiencing the highs and lows and celebrating milestones together ',
  'Investment'),
 ('startups utilize investments to enhance their product or service offerings improve user experience and deliver exceptional value to customers ',
  'Investment'),
 ('investments fuel the hiring efforts of startups empowering them to recruit top talent build diverse teams and foster a culture of innovation ',
  'Investment'),
 ('investing in startups offers the chance to support disruptive technologies that have the potential to reshape industries and improve lives ',
  'Investment'),
 ('startups use investments to implement effective marketing strategies create brand awareness and establish a strong market presence ',
  'Investment'),
 ('investments provide startups with the necessary capital to scale their operations expand into new geographies and capture a larger market share ',
  'Investment'),
 ('investing in startups allows you to diversify your investment portfolio tapping into high growth opportunities beyond traditional asset classes ',
  'Investment'),
 ('startups leverage investments to build robust customer acquisition channels drive user engagement and foster customer loyalty ',
  'Investment'),
 ('investments enable startups to invest in data analytics ai and machine learning capabilities gaining valuable insights and competitive advantages ',
  'Investment'),
 ('investing in startups is a way to support local economies job creation and foster innovation driven ecosystems ',
  'Investment'),
 ('startups utilize investments to strengthen their intellectual property portfolio protecting their innovations and establishing a defensible market position ',
  'Investment'),
 ('investments provide startups with the financial flexibility to experiment iterate and pivot their business models based on market feedback ',
  'Investment'),
 ('investing in startups offers the opportunity to be part of a vibrant community of investors entrepreneurs and industry experts ',
  'Investment'),
 ('startups rely on investments to establish robust cybersecurity measures safeguarding sensitive data and ensuring trust from customers ',
  'Investment'),
 ('investments fuel the scaling efforts of startups allowing them to increase production meet growing demand and achieve economies of scale ',
  'Investment'),
 ('investing in startups fosters innovation driving advancements in technology healthcare sustainability and other critical sectors ',
  'Investment'),
 ('startups utilize investments to conduct market research validate product market fit and refine their value proposition to attract customers ',
  'Investment'),
 ('investments enable startups to leverage partnerships and collaborations accessing shared resources expertise and networks ',
  'Investment'),
 ('investing in startups provides an avenue to support diverse founders and contribute to building an inclusive and equitable entrepreneurial ecosystem ',
  'Investment'),
 ('startups rely on investments to establish robust supply chains optimize logistics and ensure efficient operations ',
  'Investment'),
 ('investments fuel the expansion efforts of startups empowering them to enter new verticals diversify revenue streams and capture untapped markets ',
  'Investment'),
 ('i m seeking venture capital funding for my innovative startup idea ',
  'Investment'),
 ('can venusventure provide seed funding for early stage startups ',
  'Investment'),
 ('how can i pitch my business plan to venusventure s investment team ',
  'Investment'),
 ('i m looking for investors to support the growth of my technology startup ',
  'Investment'),
 ('what is the average funding amount venusventure offers to startups ',
  'Investment'),
 ('can venusventure assist with securing series a funding for my startup ',
  'Investment'),
 ('i m seeking strategic investors who can provide more than just capital ',
  'Investment'),
 ('how does venusventure evaluate the potential of a startup before investing ',
  'Investment'),
 ('are there any specific industries or sectors venusventure focuses on for investment ',
  'Investment'),
 ('can venusventure provide mentorship and guidance along with the investment ',
  'Investment'),
 ('mentors and advisors play a vital role in guiding startups through the complexities of entrepreneurship offering invaluable insights and expertise ',
  'Mentors_and_advisors'),
 ('startups greatly benefit from the wisdom and experience of mentors and advisors who can provide strategic direction and help navigate challenges ',
  'Mentors_and_advisors'),
 ('having access to knowledgeable mentors and advisors gives startups a competitive advantage by accelerating their learning curve and avoiding common pitfalls ',
  'Mentors_and_advisors'),
 ('mentors and advisors provide startups with a fresh perspective challenging assumptions and pushing them to think creatively and critically about their business ',
  'Mentors_and_advisors'),
 ('startups often face uncertainties and ambiguity and mentors and advisors provide much needed clarity helping them make informed decisions ',
  'Mentors_and_advisors'),
 ('mentors and advisors act as a sounding board for startups offering constructive feedback and helping them refine their ideas and strategies ',
  'Mentors_and_advisors'),
 ('the guidance and support of mentors and advisors can help startups build a strong foundation establish best practices and set realistic goals ',
  'Mentors_and_advisors'),
 ('startups can tap into the networks of mentors and advisors accessing valuable connections partnerships and opportunities for growth ',
  'Mentors_and_advisors'),
 ('mentors and advisors bring a wealth of industry knowledge and insights helping startups stay up to date with market trends and emerging technologies ',
  'Mentors_and_advisors'),
 ('for startups seeking investment mentors and advisors can enhance their credibility and provide introductions to potential investors and funding sources ',
  'Mentors_and_advisors'),
 ('the mentorship and guidance of experienced professionals can instill confidence in startup founders empowering them to overcome challenges and persevere ',
  'Mentors_and_advisors'),
 ('mentors and advisors provide startups with a valuable support system offering encouragement motivation and accountability along the entrepreneurial journey ',
  'Mentors_and_advisors'),
 ('startups can leverage the expertise of mentors and advisors to build a strong team attract top talent and foster a culture of growth and innovation ',
  'Mentors_and_advisors'),
 ('mentors and advisors act as trusted confidants for startup founders providing a safe space to discuss ideas concerns and personal development ',
  'Mentors_and_advisors'),
 ('the mentorship of seasoned entrepreneurs can help startups anticipate and navigate common hurdles accelerating their path to success ',
  'Mentors_and_advisors'),
 ('mentors and advisors bring diverse perspectives to the table challenging assumptions and helping startups think outside the box ',
  'Mentors_and_advisors'),
 ('startups can learn from the successes and failures of mentors and advisors gaining valuable lessons and avoiding costly mistakes ',
  'Mentors_and_advisors'),
 ('mentors and advisors provide startups with access to a wealth of industry specific knowledge helping them make informed decisions and stay ahead of the curve ',
  'Mentors_and_advisors'),
 ('for startups entering new markets or industries mentors and advisors with domain expertise can provide invaluable guidance and market insights ',
  'Mentors_and_advisors'),
 ('the mentorship and guidance of experienced professionals can help startups build resilience adaptability and a strong entrepreneurial mindset ',
  'Mentors_and_advisors'),
 ('startups require mentors and advisors who have deep industry knowledge and experience to provide strategic guidance and insights ',
  'Mentors_and_advisors'),
 ('mentors and advisors should have a strong track record of success in startups or entrepreneurship demonstrating their ability to navigate challenges and drive growth ',
  'Mentors_and_advisors'),
 ('startups need mentors and advisors who can challenge their assumptions ask critical questions and provide objective feedback to refine their business strategies ',
  'Mentors_and_advisors'),
 ('mentors and advisors should possess excellent communication skills to effectively convey their expertise and guidance to startup founders and teams ',
  'Mentors_and_advisors'),
 ('startups require mentors and advisors who are well connected in the industry able to open doors to valuable networks partnerships and funding opportunities ',
  'Mentors_and_advisors'),
 ('mentors and advisors should have a genuine passion for startups and entrepreneurship offering their support and guidance with a vested interest in the startup s success ',
  'Mentors_and_advisors'),
 ('startups need mentors and advisors who are adaptable and flexible able to navigate the rapidly changing business landscape and help startups stay ahead ',
  'Mentors_and_advisors'),
 ('mentors and advisors should have a deep understanding of market trends emerging technologies and customer preferences to guide startups in making informed decisions ',
  'Mentors_and_advisors'),
 ('startups require mentors and advisors who can provide constructive criticism challenging startup founders to continuously improve and refine their business models ',
  'Mentors_and_advisors'),
 ('mentors and advisors should be able to offer valuable insights and best practices in areas such as fundraising marketing operations and talent acquisition ',
  'Mentors_and_advisors'),
 ('startups need mentors and advisors who can help them identify and seize opportunities guiding them in strategic partnerships collaborations and market expansions ',
  'Mentors_and_advisors'),
 ('mentors and advisors should have a strong understanding of the startup s target market customers and competitive landscape to provide relevant guidance ',
  'Mentors_and_advisors'),
 ('startups require mentors and advisors who can help them build a strong team attract and retain top talent and create a positive and inclusive work culture ',
  'Mentors_and_advisors'),
 ('mentors and advisors should possess excellent problem solving skills helping startups navigate challenges overcome obstacles and make effective decisions ',
  'Mentors_and_advisors'),
 ('startups need mentors and advisors who can provide guidance on legal and regulatory compliance intellectual property protection and risk management ',
  'Mentors_and_advisors'),
 ('mentors and advisors should be supportive and empathetic understanding the unique challenges and pressures faced by startup founders and teams ',
  'Mentors_and_advisors'),
 ('startups require mentors and advisors who can help them develop a scalable business model monetization strategies and a path to sustainable growth and profitability ',
  'Mentors_and_advisors'),
 ('mentors and advisors should have a growth mindset encouraging startups to embrace experimentation learn from failures and iterate on their ideas and products ',
  'Mentors_and_advisors'),
 ('startups need mentors and advisors who are committed and available willing to invest time and effort in supporting the startup s growth and success ',
  'Mentors_and_advisors'),
 ('mentors and advisors should possess strong leadership and mentorship skills guiding startups in building resilience fostering innovation and developing their own leadership capabilities ',
  'Mentors_and_advisors'),
 ('in our startup we are actively seeking mentors and advisors who can provide us with guidance and support ',
  'Mentors_and_advisors'),
 ('i m looking for a mentor who can provide guidance in scaling my startup ',
  'Mentors_and_advisors'),
 ('can venusventure connect me with mentors who have experience in e commerce ',
  'Mentors_and_advisors'),
 ('how can i request mentorship from successful entrepreneurs associated with venusventure ',
  'Mentors_and_advisors'),
 ('are there any specific criteria for being eligible for mentorship at venusventure ',
  'Mentors_and_advisors'),
 ('i need guidance in fundraising strategies from experienced mentors ',
  'Mentors_and_advisors'),
 ('can venusventure provide mentorship in product development and market fit ',
  'Mentors_and_advisors'),
 ('are there any mentorship programs or initiatives for female entrepreneurs ',
  'Mentors_and_advisors'),
 ('how can i access industry specific mentors through venusventure ',
  'Mentors_and_advisors'),
 ('are there any networking events or workshops where i can meet potential mentors ',
  'Mentors_and_advisors'),
 ('can venusventure help me find mentors with expertise in international expansion ',
  'Mentors_and_advisors'),
 ('startups should proactively seek feedback and insights from their target markets to continuously improve their products and customer experience ',
  'Target_Markets'),
 ('identifying the influencers and key opinion leaders within their target markets can help startups amplify their brand reach and credibility ',
  'Target_Markets'),
 ('startups need to adapt their pricing strategies to align with the purchasing power and willingness to pay of their target markets ',
  'Target_Markets'),
 ('startups should conduct market segmentation to identify distinct groups within their target markets and tailor their strategies accordingly ',
  'Target_Markets'),
 ('understanding the geographic location and distribution channels of their target markets helps startups optimize their logistics and distribution processes ',
  'Target_Markets'),
 ('startups need to stay updated on the latest market trends and consumer behavior within their target markets to remain competitive ',
  'Target_Markets'),
 ('identifying the pain points and unmet needs of their target markets allows startups to develop innovative solutions that resonate with customers ',
  'Target_Markets'),
 ('startups should consider the psychographic factors such as values interests and lifestyles of their target markets when crafting their brand messaging ',
  'Target_Markets'),
 ('understanding the purchasing behavior and decision making process of their target markets helps startups design effective sales and marketing funnels ',
  'Target_Markets'),
 ('startups should leverage social media and digital marketing channels to reach and engage with their target markets effectively ',
  'Target_Markets'),
 ('identifying the competitive advantages and unique selling points that appeal to their target markets allows startups to differentiate themselves ',
  'Target_Markets'),
 ('startups should conduct customer surveys and interviews to gather valuable insights and feedback from their target markets ',
  'Target_Markets'),
 ('i need assistance in conducting market research for my startup s target audience ',
  'Target_Markets'),
 ('can venusventure provide insights into emerging market trends and consumer behavior ',
  'Target_Markets'),
 ('how can i validate my startup s product market fit with the help of venusventure ',
  'Target_Markets'),
 ('are there any resources or tools available to analyze market demand and competition ',
  'Target_Markets'),
 ('can venusventure help me identify potential customers and target markets ',
  'Target_Markets'),
 ('i want to understand the market landscape in a specific industry segment ',
  'Target_Markets'),
 ('does venusventure provide access to industry reports or market analysis ',
  'Target_Markets'),
 ('how can i stay updated with the latest market insights through venusventure ',
  'Target_Markets'),
 ('can venusventure assist in identifying strategic partnerships within my target market ',
  'Target_Markets'),
 ('are there any specific geographic regions venusventure focuses on for market analysis ',
  'Target_Markets'),
 ('i would like to submit my project proposal to venusventure for consideration ',
  'project viability'),
 ('can venusventure provide feedback on my startup s business model ',
  'project viability'),
 ('how can i showcase the potential impact of my project to venusventure ',
  'project viability'),
 ('are there specific industries or technologies venusventure is interested in for projects ',
  'project viability'),
 ('can you guide me on creating an effective project presentation for venusventure ',
  'project viability'),
 ('i want to pitch my social impact project to venusventure s project evaluation team ',
  'project viability'),
 ('is there a specific format or template to follow for project submissions ',
  'project viability'),
 ('can venusventure offer resources or expertise to refine my project s execution plan ',
  'project viability'),
 ('how can i increase the chances of my project being accepted by venusventure ',
  'project viability'),
 ('what are the key factors venusventure considers while evaluating project proposals ',
  'project viability'),
 ('how does venusventure align its investments with its mission and values ',
  'mission'),
 ('can you provide examples of startups that resonate with venusventure s mission ',
  'mission'),
 ('what is venusventure s long term vision for supporting the startup ecosystem ',
  'mission'),
 ('how does venusventure contribute to social and environmental sustainability ',
  'mission'),
 ('can you explain the social impact criteria venusventure applies to startup evaluation ',
  'mission'),
 ('what steps does venusventure take to ensure ethical and responsible investments ',
  'mission'),
 ('does venusventure prioritize startups with a strong mission driven culture ',
  'mission'),
 ('how can i demonstrate that my startup s mission aligns with venusventure s values ',
  'mission'),
 ('can venusventure support startups focusing on underserved communities ',
  'mission'),
 ('what are the expectations for startups in terms of fulfilling venusventure s mission ',
  'mission'),
 ('i m looking for educational resources to enhance my startup s marketing strategies ',
  'upskilling_Reskilling'),
 ('can venusventure recommend online courses for entrepreneurs on financial management ',
  'upskilling_Reskilling'),
 ('are there workshops or training sessions available to improve my pitching skills ',
  'upskilling_Reskilling'),
 ('can venusventure provide guidance on developing a strong business plan ',
  'upskilling_Reskilling'),
 ('i want to learn more about startup growth strategies through venusventure s educational programs ',
  'upskilling_Reskilling'),
 ('how can i access resources on legal and regulatory aspects relevant to startups ',
  'upskilling_Reskilling'),
 ('can venusventure offer educational support in emerging technologies like ai or blockchain ',
  'upskilling_Reskilling'),
 ('are there any mentor led educational initiatives for early stage startups ',
  'upskilling_Reskilling'),
 ('can i get access to webinars or expert talks on scaling a startup ',
  'upskilling_Reskilling'),
 ('what educational opportunities does venusventure provide for startup founders beyond funding ',
  'upskilling_Reskilling'),
 ('strong leadership and mentorship skills are essential for mentors and advisors to champion upskilling and reskilling initiatives enabling startups to adapt to evolving market demands and seize growth opportunities ',
  'upskilling_Reskilling'),
 ('mentors and advisors with expertise in upskilling and reskilling can empower startups to embrace lifelong learning equipping them with the necessary skills to thrive in a rapidly changing business landscape ',
  'upskilling_Reskilling'),
 ('by providing guidance on upskilling and reskilling strategies mentors and advisors play a critical role in helping startups future proof their workforce and enhance their competitiveness ',
  'upskilling_Reskilling'),
 ('startups benefit from mentors and advisors who prioritize upskilling and reskilling as they can assist in identifying skill gaps designing training programs and fostering a culture of continuous learning ',
  'upskilling_Reskilling'),
 ('mentors and advisors should stay updated with industry trends and emerging technologies to effectively guide startups in upskilling and reskilling for future success ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling initiatives led by mentors and advisors help startups build a versatile and adaptable team capable of navigating challenges and driving innovation ',
  'upskilling_Reskilling'),
 ('mentors and advisors with a focus on upskilling and reskilling can support startups in attracting and retaining top talent creating a learning environment that fosters personal and professional growth ',
  'upskilling_Reskilling'),
 ('by instilling a culture of upskilling and reskilling mentors and advisors contribute to the long term sustainability and success of startups by continuously improving their capabilities and staying ahead of the competition ',
  'upskilling_Reskilling'),
 ('startups can leverage upskilling and reskilling programs facilitated by mentors and advisors to enhance employee engagement and job satisfaction leading to higher productivity and retention rates ',
  'upskilling_Reskilling'),
 ('mentors and advisors can guide startups in identifying relevant upskilling and reskilling opportunities such as online courses workshops and industry certifications to keep their team s skills up to date ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling initiatives supported by mentors and advisors help startups build a culture of continuous improvement fostering creativity innovation and a forward thinking mindset ',
  'upskilling_Reskilling'),
 ('mentors and advisors play a vital role in assessing the skill sets of startup teams and identifying areas where upskilling and reskilling efforts can be directed for maximum impact ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling create a competitive advantage by developing a workforce capable of embracing new technologies adapting to market changes and seizing emerging opportunities ',
  'upskilling_Reskilling'),
 ('mentors and advisors can provide guidance on incorporating upskilling and reskilling programs into the overall business strategy of startups aligning skill development with organizational goals ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling initiatives supported by mentors and advisors foster a growth mindset within startups encouraging employees to embrace learning take on new challenges and continuously improve their skills ',
  'upskilling_Reskilling'),
 ('mentors and advisors with expertise in upskilling and reskilling can help startups create personalized learning paths for their employees addressing individual skill gaps and nurturing talent development ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling demonstrate their commitment to employee development attracting top talent and creating a reputation as an employer of choice in the industry ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in measuring the effectiveness of upskilling and reskilling programs tracking key performance indicators to evaluate the impact on individual and organizational growth ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts guided by mentors and advisors can help startups adapt to digital transformation equipping their workforce with the digital skills necessary to thrive in the modern business landscape ',
  'upskilling_Reskilling'),
 ('mentors and advisors can help startups identify emerging skill requirements in their industry and design proactive upskilling and reskilling strategies to stay ahead of the curve ',
  'upskilling_Reskilling'),
 ('startups that foster a learning culture through upskilling and reskilling initiatives attract motivated and self driven individuals who are eager to develop their skills and contribute to the company s growth ',
  'upskilling_Reskilling'),
 ('mentors and advisors can connect startups with external training providers industry experts and educational resources to facilitate effective upskilling and reskilling programs ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling programs supported by mentors and advisors enable startups to address skill gaps internally reducing the need for costly external hires and promoting internal talent growth ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in creating a roadmap for upskilling and reskilling outlining the necessary steps resources and milestones to achieve continuous learning and development ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling create a positive and dynamic work environment where employees feel valued motivated and empowered to contribute to the company s success ',
  'upskilling_Reskilling'),
 ('mentors and advisors can introduce startups to industry best practices and new technologies through upskilling and reskilling initiatives enabling them to innovate and stay ahead of their competitors ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts guided by mentors and advisors help startups build a diverse and inclusive workforce promoting equal opportunities for professional growth and development ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in creating upskilling and reskilling budgets allocating resources effectively to ensure a sustainable investment in talent development ',
  'upskilling_Reskilling'),
 ('in today s rapidly evolving business landscape upskilling and reskilling are essential for startups to stay competitive and adapt to changing market demands ',
  'upskilling_Reskilling'),
 ('startups that embrace upskilling and reskilling as a strategic priority demonstrate a commitment to continuous learning and improvement fostering a culture of innovation and agility ',
  'upskilling_Reskilling'),
 ('mentors and advisors can help startups identify the specific skills and knowledge gaps within their team guiding them in implementing targeted upskilling and reskilling initiatives ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts supported by mentors and advisors enable startups to future proof their workforce ensuring they have the capabilities to thrive in a rapidly changing business environment ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling create a positive work environment that promotes employee growth job satisfaction and overall organizational success ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in identifying emerging technologies and trends guiding them in upskilling and reskilling efforts to leverage these opportunities ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling programs supported by mentors and advisors empower startups to unlock the full potential of their team members leading to increased productivity and innovation ',
  'upskilling_Reskilling'),
 ('startups that provide upskilling and reskilling opportunities attract and retain top talent as professionals are more inclined to join companies that invest in their professional development ',
  'upskilling_Reskilling'),
 ('mentors and advisors with expertise in upskilling and reskilling can help startups design personalized learning paths tailored to individual employee needs maximizing the impact of skill development ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling initiatives supported by mentors and advisors enable startups to build a skilled workforce that can tackle complex challenges and drive sustainable growth ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling foster a culture of continuous learning where employees are encouraged to acquire new skills and knowledge to adapt to evolving market trends ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in creating a training roadmap that outlines the necessary upskilling and reskilling activities to address current and future skill requirements ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts guided by mentors and advisors help startups build internal expertise reducing reliance on external consultants and enabling cost effective problem solving ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling gain a competitive edge by equipping their employees with the latest industry knowledge tools and techniques ',
  'upskilling_Reskilling'),
 ('mentors and advisors can provide guidance on the most relevant upskilling and reskilling programs and certifications available ensuring startups invest in the right skill development opportunities ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling initiatives supported by mentors and advisors contribute to the long term sustainability of startups as they create a learning culture that adapts to evolving market dynamics ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling foster employee engagement and loyalty as team members feel valued and supported in their professional growth and development ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in leveraging upskilling and reskilling as a strategic advantage aligning skill development with the company s growth objectives and market positioning ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts supported by mentors and advisors enable startups to expand their service offerings enter new markets and seize emerging business opportunities ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling create a culture of adaptability and resilience equipping their team members with the skills needed to navigate uncertainties and challenges ',
  'upskilling_Reskilling'),
 ('mentors and advisors can help startups assess the current skill gaps and future skill needs guiding them in designing comprehensive upskilling and reskilling strategies ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling initiatives supported by mentors and advisors foster a growth mindset within startups encouraging employees to embrace learning opportunities and explore new areas of expertise ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling enhance their organizational capacity as employees gain the knowledge and skills to take on additional responsibilities and contribute to the company s growth ',
  'upskilling_Reskilling'),
 ('mentors and advisors can help startups identify emerging industry trends and technologies that require specialized skills guiding them in upskilling and reskilling efforts to meet market demands ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling programs supported by mentors and advisors promote a culture of collaboration and knowledge sharing as employees learn from each other s expertise and experiences ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling foster a culture of innovation as employees develop the skills and mindset to explore new ideas experiment and drive creative solutions ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in identifying cost effective upskilling and reskilling opportunities such as online courses workshops and industry events maximizing the value of skill development investments ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts supported by mentors and advisors improve startups ability to attract external partnerships and collaborations as they demonstrate a commitment to staying at the forefront of industry developments ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling create a talent pipeline within their organization nurturing the growth and advancement of their employees and reducing the need for external talent acquisition ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in developing upskilling and reskilling frameworks that align with the company s strategic goals ensuring that skill development efforts directly contribute to business success ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling programs supported by mentors and advisors foster a culture of lifelong learning within startups empowering employees to adapt to future disruptions and seize emerging opportunities ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling create a positive employer brand attracting top talent who value continuous learning and professional development opportunities ',
  'upskilling_Reskilling'),
 ('mentors and advisors can provide guidance on upskilling and reskilling methods and technologies enabling startups to leverage the most effective and efficient learning approaches for their teams ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts supported by mentors and advisors equip startups with a versatile workforce capable of handling diverse tasks and adapting to changing customer needs ',
  'upskilling_Reskilling'),
 ('startups that prioritize upskilling and reskilling foster a culture of empowerment as employees gain the knowledge and skills necessary to take ownership of their work and drive meaningful impact ',
  'upskilling_Reskilling'),
 ('mentors and advisors can assist startups in assessing the roi return on investment of upskilling and reskilling initiatives ensuring that the resources invested yield tangible benefits for the company ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling programs supported by mentors and advisors contribute to startups long term sustainability by ensuring that the workforce remains relevant and adaptable in a rapidly evolving business landscape ',
  'upskilling_Reskilling'),
 ('startups that invest in upskilling and reskilling cultivate a culture of continuous improvement as employees constantly update their skills and knowledge to meet evolving market demands and customer expectations ',
  'upskilling_Reskilling'),
 ('mentors and advisors can provide guidance on identifying the most crucial skills and competencies needed for startup success helping prioritize upskilling and reskilling efforts accordingly ',
  'upskilling_Reskilling'),
 ('upskilling and reskilling efforts supported by mentors and advisors enable startups to build a diverse and inclusive workforce as employees from different backgrounds and experiences develop the skills needed for career advancement ',
  'upskilling_Reskilling'),
 ('developing a high quality and innovative product is crucial for the success of a startup as it forms the foundation of its value proposition ',
  'product'),
 ('mentors and advisors can provide valuable insights and guidance on product development strategies helping startups create compelling and market ready offerings ',
  'product'),
 ('startups need to conduct thorough market research to understand customer needs and preferences enabling them to design products that address specific pain points and provide unique solutions ',
  'product'),
 ('mentors and advisors with domain expertise can assist startups in refining their product ideas validating market demand and identifying potential product market fit ',
  'product'),
 ('creating a minimum viable product mvp allows startups to gather feedback from early adopters and iterate on their product ensuring it meets customer expectations and delivers value ',
  'product'),
 ('startups should focus on building scalable and flexible products that can adapt to changing market dynamics and customer requirements ',
  'product'),
 ('mentors and advisors can help startups define their product roadmap prioritize features and align product development efforts with business objectives ',
  'product'),
 ('startups need to establish a strong product development process that involves cross functional collaboration agile methodologies and continuous improvement ',
  'product'),
 ('mentors and advisors can assist startups in leveraging emerging technologies and trends to enhance their product offerings and gain a competitive edge ',
  'product'),
 ('creating a compelling user experience ux and intuitive interface is essential for startups to differentiate their products and delight customers ',
  'product'),
 ('startups should adopt a customer centric approach in product development seeking customer feedback and incorporating it into product iterations ',
  'product'),
 ('mentors and advisors can guide startups in defining their unique selling proposition usp and positioning their product in the market to attract target customers ',
  'product'),
 ('startups need to consider the scalability and sustainability of their products ensuring they can meet the growing demands of a rapidly expanding customer base ',
  'product'),
 ('mentors and advisors can assist startups in conducting competitive analysis to identify market gaps and develop products that offer superior value compared to existing solutions ',
  'product'),
 ('startups should invest in continuous product innovation to stay ahead of competitors and meet evolving customer needs ',
  'product'),
 ('mentors and advisors can provide guidance on product pricing strategies helping startups strike the right balance between value affordability and profitability ',
  'product'),
 ('startups should establish strong product quality control processes to ensure that their offerings meet high standards and deliver a consistent user experience ',
  'product'),
 ('mentors and advisors can help startups create effective product marketing and messaging strategies enabling them to communicate the value and benefits of their offerings to customers ',
  'product'),
 ('startups should continuously monitor market trends and customer feedback to identify opportunities for product enhancements new features and product line extensions ',
  'product'),
 ('mentors and advisors can support startups in building a strong product development team attracting top talent with the necessary expertise and skills ',
  'product'),
 ('startups must prioritize user feedback and data analytics to drive data informed product decisions ensuring that their offerings meet customer expectations and achieve market success ',
  'product'),
 ('mentors and advisors can assist startups in conducting user testing and usability studies to gather valuable insights and make iterative improvements to their product ',
  'product'),
 ('startups should invest in robust product documentation and knowledge sharing practices to ensure seamless onboarding and support for their customers ',
  'product'),
 ('mentors and advisors can help startups define key performance indicators kpis and metrics to measure the success and impact of their product facilitating data driven decision making ',
  'product'),
 ('startups should adopt an agile product development approach allowing for iterative development quick feedback loops and accelerated time to market ',
  'product'),
 ('mentors and advisors can guide startups in conducting market segmentation and targeting exercises to identify specific customer segments and tailor their product offerings accordingly ',
  'product'),
 ('startups need to stay updated with industry trends emerging technologies and customer preferences to ensure their products remain relevant and competitive in the market ',
  'product'),
 ('mentors and advisors can provide insights on product differentiation strategies helping startups identify unique features and value propositions that set them apart from competitors ',
  'product'),
 ('startups should prioritize building a scalable and adaptable product infrastructure to support future growth and expansion ',
  'product'),
 ('mentors and advisors can assist startups in creating effective product pricing models that align with market demand competitive landscape and revenue goals ',
  'product'),
 ('startups should conduct thorough competitive analysis to understand competitor products identify gaps and position their offerings to capture market share ',
  'product'),
 ('mentors and advisors can guide startups in implementing user feedback loops continuous product testing and improvement cycles to ensure ongoing product excellence ',
  'product'),
 ('startups should consider the ethical implications of their product development and strive for responsible and sustainable solutions that benefit both customers and society ',
  'product'),
 ('mentors and advisors can help startups navigate intellectual property issues and ensure proper protection of their product innovations through patents trademarks or copyrights ',
  'product'),
 ('startups should explore strategic partnerships and collaborations to enhance their product capabilities access new markets and drive mutual growth ',
  'product'),
 ('mentors and advisors can support startups in crafting effective product launch strategies including timing target audience marketing channels and promotional activities ',
  'product'),
 ('startups should continuously gather and analyze customer feedback to identify areas for product improvement address pain points and enhance overall user satisfaction ',
  'product'),
 ('mentors and advisors can provide guidance on product distribution and channel strategies helping startups reach their target customers effectively and efficiently ',
  'product'),
 ('startups should invest in user education and product training programs to empower customers and maximize the value they derive from the product ',
  'product'),
 ('mentors and advisors can assist startups in building a strong product brand and reputation through effective storytelling brand positioning and customer advocacy ',
  'product'),
 ('startups should conduct thorough market research to identify customer needs pain points and opportunities for product innovation ',
  'product'),
 ('mentors and advisors can help startups develop a product roadmap outlining key milestones timelines and resource requirements for successful product development ',
  'product'),
 ('startups should leverage user centered design principles to create intuitive and seamless product experiences that delight and engage customers ',
  'product'),
 ('mentors and advisors can provide guidance on product scalability and extensibility ensuring that the product can grow and adapt to evolving market demands ',
  'product'),
 ('startups should prioritize user privacy and data security in the design and development of their products building trust with customers ',
  'product'),
 ('mentors and advisors can assist startups in defining a clear value proposition for their product articulating the unique benefits and value it offers to customers ',
  'product'),
 ('startups should foster a culture of innovation and experimentation encouraging employees to contribute ideas and drive continuous product improvement ',
  'product'),
 ('mentors and advisors can help startups optimize their product pricing strategy by considering factors such as cost structure perceived value and competitive landscape ',
  'product'),
 ('startups should actively seek customer feedback and incorporate it into their product development process ensuring that their solutions meet real customer needs ',
  'product'),
 ('mentors and advisors can guide startups in creating a minimum viable product mvp and iterative development approach enabling them to validate assumptions and gather early user feedback ',
  'product'),
 ('startups should focus on building a user centric product roadmap that aligns with customer goals preferences and pain points ',
  'product'),
 ('mentors and advisors can provide insights on product packaging and branding strategies helping startups create compelling product visuals and messaging ',
  'product'),
 ('startups should invest in continuous product innovation and feature enhancements to stay ahead of competitors and meet evolving customer expectations ',
  'product'),
 ('mentors and advisors can assist startups in conducting market validation exercises including customer interviews surveys and prototype testing to gather feedback and validate product market fit ',
  'product'),
 ('startups should monitor key performance indicators kpis related to their product such as customer acquisition retention and satisfaction to measure product success ',
  'product'),
 ('mentors and advisors can provide guidance on product localization and internationalization strategies helping startups tailor their offerings to specific geographic markets ',
  'product'),
 ('startups should establish a product feedback loop with their customers encouraging them to provide suggestions ideas and insights for product enhancement ',
  'product'),
 ('mentors and advisors can support startups in conducting competitive benchmarking and feature analysis to identify areas of product improvement and differentiation ',
  'product'),
 ('startups should prioritize continuous learning and experimentation allowing them to adapt their product strategy based on market feedback and trends ',
  'product'),
 ('mentors and advisors can help startups develop a product launch plan including marketing strategies target audience identification and promotional activities ',
  'product'),
 ('understanding the target market s demand and willingness to pay is essential for evaluating the project viability and potential revenue generation ',
  'project viability'),
 ('startups should consider the legal and regulatory landscape to assess the project viability and ensure compliance with relevant laws and regulations ',
  'project viability'),
 ('evaluating the availability and cost of necessary resources such as skilled talent infrastructure and technology is crucial for determining the project viability ',
  'project viability'),
 ('assessing the competitive landscape and identifying unique selling points are key steps in evaluating the project viability and market positioning of a startup ',
  'project viability'),
 ('startups need to evaluate the scalability and growth potential of their business model to determine the long term project viability and sustainability ',
  'project viability'),
 ('analyzing the potential risks and challenges such as market volatility or technological disruptions is essential for assessing the project viability and developing risk mitigation strategies ',
  'project viability'),
 ('startups should conduct customer validation and feedback to assess the market fit and acceptance of their product or service contributing to the evaluation of project viability ',
  'project viability'),
 ('evaluating the cost structure revenue streams and profitability projections is crucial for determining the financial viability and sustainability of the project ',
  'project viability'),
 ('startups should evaluate the potential strategic partnerships and collaborations that can enhance the project viability and provide access to resources and distribution channels ',
  'project viability'),
 ('assessing the project timeline and milestones is important to understand the feasibility and time to market contributing to the evaluation of project viability ',
  'project viability'),
 ('startups should analyze the potential impact of technological advancements and industry trends to assess the project viability and future relevance of their solution ',
  'project viability'),
 ('evaluating the funding requirements and potential investment opportunities is crucial for determining the financial viability and scalability of the project ',
  'project viability'),
 ('startups should consider the social and environmental impact of their project to assess its viability and alignment with sustainability goals ',
  'project viability'),
 ('assessing the project team s capabilities and expertise is essential for evaluating the project viability and ensuring the availability of necessary skills for successful execution ',
  'project viability'),
 ('startups should conduct a thorough cost benefit analysis to evaluate the potential returns and profitability of the project contributing to its viability assessment ',
  'project viability'),
 ('evaluating the intellectual property landscape and potential barriers to entry is important for assessing the project viability and protecting the startup s innovations ',
  'project viability'),
 ('startups should consider the target customer segments and their buying behavior to evaluate the project viability and market demand for their offering ',
  'project viability'),
 ('assessing the project s alignment with the startup s vision mission and values is crucial for evaluating its viability and ensuring strategic coherence ',
  'project viability'),
 ('startups should evaluate the potential exit strategies and return on investment to assess the project viability and provide insights to potential investors ',
  'project viability'),
 ('analyzing the potential market size and growth trends is important for assessing the project viability and market opportunity for a startup ',
  'project viability'),
 ('startups should evaluate the potential impact of regulatory changes and government policies on the project viability and market conditions ',
  'project viability'),
 ('assessing the scalability and adaptability of the project to changing market dynamics and customer preferences is crucial for its long term viability ',
  'project viability'),
 ('startups should evaluate the availability and effectiveness of distribution channels to reach their target market and assess the project viability ',
  'project viability'),
 ('analyzing the potential technological and operational risks such as cybersecurity threats or supply chain disruptions is important for assessing the project viability and risk management ',
  'project viability'),
 ('startups should consider the potential social and economic benefits their project can bring to stakeholders to assess its viability and societal impact ',
  'project viability'),
 ('assessing the potential scalability challenges and resource requirements as the project grows is important for evaluating its long term viability and success ',
  'project viability'),
 ('startups should evaluate the market saturation and competition intensity to assess the project viability and identify strategies for differentiation ',
  'project viability'),
 ('analyzing the project s potential impact on job creation skill development and economic growth is important for evaluating its viability and social contribution ',
  'project viability'),
 ('startups should evaluate the potential demand volatility and market cyclicality to assess the project viability and develop appropriate risk mitigation strategies ',
  'project viability'),
 ('assessing the project s alignment with emerging trends such as sustainability digitalization or remote work is crucial for evaluating its viability and future relevance ',
  'project viability'),
 ('understanding the target market s demand and willingness to pay is essential for evaluating the project viability and potential revenue generation ',
  'project viability'),
 ('startups should consider the legal and regulatory landscape to assess the project viability and ensure compliance with relevant laws and regulations ',
  'project viability'),
 ('evaluating the availability and cost of necessary resources such as skilled talent infrastructure and technology is crucial for determining the project viability ',
  'project viability'),
 ('assessing the competitive landscape and identifying unique selling points are key steps in evaluating the project viability and market positioning of a startup ',
  'project viability'),
 ('startups need to evaluate the scalability and growth potential of their business model to determine the long term project viability and sustainability ',
  'project viability'),
 ('analyzing the potential risks and challenges such as market volatility or technological disruptions is essential for assessing the project viability and developing risk mitigation strategies ',
  'project viability'),
 ('startups should conduct customer validation and feedback to assess the market fit and acceptance of their product or service contributing to the evaluation of project viability ',
  'project viability'),
 ('evaluating the cost structure revenue streams and profitability projections is crucial for determining the financial viability and sustainability of the project ',
  'project viability'),
 ('startups should evaluate the potential strategic partnerships and collaborations that can enhance the project viability and provide access to resources and distribution channels ',
  'project viability'),
 ('assessing the project timeline and milestones is important to understand the feasibility and time to market contributing to the evaluation of project viability ',
  'project viability'),
 ('startups should analyze the potential impact of technological advancements and industry trends to assess the project viability and future relevance of their solution ',
  'project viability'),
 ('evaluating the funding requirements and potential investment opportunities is crucial for determining the financial viability and scalability of the project ',
  'project viability'),
 ('startups should consider the social and environmental impact of their project to assess its viability and alignment with sustainability goals ',
  'project viability'),
 ('assessing the project team s capabilities and expertise is essential for evaluating the project viability and ensuring the availability of necessary skills for successful execution ',
  'project viability'),
 ('startups should conduct a thorough cost benefit analysis to evaluate the potential returns and profitability of the project contributing to its viability assessment ',
  'project viability'),
 ('evaluating the intellectual property landscape and potential barriers to entry is important for assessing the project viability and protecting the startup s innovations ',
  'project viability'),
 ('startups should consider the target customer segments and their buying behavior to evaluate the project viability and market demand for their offering ',
  'project viability'),
 ('assessing the project s alignment with the startup s vision mission and values is crucial for evaluating its viability and ensuring strategic coherence ',
  'project viability'),
 ('startups should evaluate the potential exit strategies and return on investment to assess the project viability and provide insights to potential investors ',
  'project viability'),
 ('analyzing the potential market size and growth trends is important for assessing the project viability and market opportunity for a startup ',
  'project viability'),
 ('startups should evaluate the potential impact of regulatory changes and government policies on the project viability and market conditions ',
  'project viability'),
 ('assessing the scalability and adaptability of the project to changing market dynamics and customer preferences is crucial for its long term viability ',
  'project viability'),
 ('startups should evaluate the availability and effectiveness of distribution channels to reach their target market and assess the project viability ',
  'project viability'),
 ('analyzing the potential technological and operational risks such as cybersecurity threats or supply chain disruptions is important for assessing the project viability and risk management ',
  'project viability'),
 ('startups should consider the potential social and economic benefits their project can bring to stakeholders to assess its viability and societal impact ',
  'project viability'),
 ('assessing the potential scalability challenges and resource requirements as the project grows is important for evaluating its long term viability and success ',
  'project viability'),
 ('startups should evaluate the market saturation and competition intensity to assess the project viability and identify strategies for differentiation ',
  'project viability'),
 ('analyzing the project s potential impact on job creation skill development and economic growth is important for evaluating its viability and social contribution ',
  'project viability'),
 ('startups should evaluate the potential demand volatility and market cyclicality to assess the project viability and develop appropriate risk mitigation strategies ',
  'project viability'),
 ('assessing the project s alignment with emerging trends such as sustainability digitalization or remote work is crucial for evaluating its viability and future relevance ',
  'project viability'),
 ('startups should evaluate the scalability and efficiency of their operational processes to assess the project viability and ensure smooth execution ',
  'project viability'),
 ('analyzing the potential market barriers and entry requirements is important for assessing the project viability and determining the feasibility of market entry ',
  'project viability'),
 ('startups should evaluate the potential impact of economic factors such as inflation rates or exchange rate fluctuations on the project viability and financial stability ',
  'project viability'),
 ('assessing the project s alignment with emerging technologies and digital transformation trends is crucial for evaluating its viability and competitiveness in the market ',
  'project viability'),
 ('startups should evaluate the potential impact of cultural and social factors on their target market to assess the project viability and adapt their strategies accordingly ',
  'project viability'),
 ('analyzing the potential scalability challenges and resource requirements as the project grows is important for evaluating its long term viability and success ',
  'project viability'),
 ('startups should evaluate the market saturation and competition intensity to assess the project viability and identify strategies for differentiation ',
  'project viability'),
 ('assessing the project s potential impact on job creation skill development and economic growth is important for evaluating its viability and social contribution ',
  'project viability'),
 ('startups should evaluate the potential demand volatility and market cyclicality to assess the project viability and develop appropriate risk mitigation strategies ',
  'project viability'),
 ('analyzing the project s potential environmental impact and sustainability practices is important for evaluating its viability and aligning with global sustainability goals ',
  'project viability'),
 ('startups should assess the potential challenges and opportunities associated with international expansion to evaluate the project viability in foreign markets ',
  'project viability'),
 ('evaluating the potential impact of demographic trends and changes in consumer preferences is crucial for assessing the project viability and market demand ',
  'project viability'),
 ('startups should evaluate the potential impact of geopolitical factors and regulatory changes on the project viability and market conditions ',
  'project viability'),
 ('assessing the project s technological readiness and potential technological dependencies is important for evaluating its viability and mitigating technical risks ',
  'project viability'),
 ('startups should evaluate the potential partnerships and collaborations that can enhance the project viability and provide access to key resources or expertise ',
  'project viability'),
 ('analyzing the potential customer acquisition cost and customer lifetime value is important for evaluating the project viability and profitability ',
  'project viability'),
 ('startups should assess the potential legal and intellectual property risks to ensure the project viability and protect their innovations and assets ',
  'project viability'),
 ('evaluating the potential impact of changing market trends and emerging technologies is crucial for assessing the project viability and market relevance ',
  'project viability'),
 ('startups should evaluate the potential impact of social media and digital marketing channels on their project s visibility and market reach to assess its viability ',
  'project viability'),
 ('assessing the project s alignment with the startup s long term vision and goals is important for evaluating its viability and strategic fit ',
  'project viability'),
 ('startups should evaluate the potential impact of economic downturns and market uncertainties on the project viability and financial stability ',
  'project viability'),
 ('analyzing the potential challenges and opportunities associated with supply chain management is important for assessing the project viability and operational efficiency ',
  'project viability'),
 ('startups should assess the potential impact of cultural and regulatory differences in international markets on the project viability and market entry strategies ',
  'project viability'),
 ('evaluating the project s alignment with sustainable development goals and environmental standards is crucial for assessing its viability and societal impact ',
  'project viability'),
 ('startups should evaluate the potential scalability challenges and resource requirements in terms of talent acquisition and workforce development for project viability ',
  'project viability'),
 ('analyzing the potential impact of changing consumer behavior and preferences on the project viability and market demand is crucial for success ',
  'project viability'),
 ('startups should assess the potential risks and opportunities associated with disruptive technologies and industry trends for project viability and innovation ',
  'project viability'),
 ('evaluating the project s alignment with ethical and social responsibility principles is important for assessing its viability and reputation in the market ',
  'project viability'),
 ('startups should evaluate the potential impact of government policies and regulations on the project viability and market conditions ',
  'project viability'),
 ('assessing the project s potential financial risks such as cash flow management or funding uncertainties is crucial for evaluating its viability and financial sustainability ',
  'project viability'),
 ('our mission is to empower small businesses with innovative technology solutions enabling them to thrive in a digital world ',
  'mission'),
 ('we are on a mission to revolutionize the healthcare industry by providing accessible and personalized telemedicine services ',
  'mission'),
 ('our mission is to create a sustainable future by developing renewable energy solutions that reduce our dependence on fossil fuels ',
  'mission'),
 ('we are dedicated to improving education worldwide by providing interactive and engaging learning platforms for students of all ages ',
  'mission'),
 ('our mission is to simplify the way people manage their finances making personal finance accessible and empowering individuals to achieve their financial goals ',
  'mission'),
 ('we are committed to revolutionizing the transportation industry through the development of autonomous vehicles and smart mobility solutions ',
  'mission'),
 ('our mission is to enhance the entertainment experience by delivering immersive virtual reality content and cutting edge gaming technology ',
  'mission'),
 ('we strive to empower women in business by providing resources mentorship and networking opportunities to support their professional growth ',
  'mission'),
 ('our mission is to eradicate hunger by leveraging technology to connect surplus food with those in need reducing food waste and ensuring food security ',
  'mission'),
 ('we are on a mission to democratize access to quality healthcare by leveraging telehealth solutions and remote patient monitoring ',
  'mission'),
 ('our mission is to revolutionize the e commerce industry by providing a seamless and personalized shopping experience for consumers worldwide ',
  'mission'),
 ('we are committed to environmental sustainability by developing eco friendly products and promoting conscious consumerism ',
  'mission'),
 ('our mission is to foster innovation and entrepreneurship by providing a supportive ecosystem and resources for aspiring startup founders ',
  'mission'),
 ('we are dedicated to promoting diversity and inclusion in the workplace creating equal opportunities for underrepresented groups ',
  'mission'),
 ('our mission is to improve global connectivity by developing affordable and accessible internet solutions for remote and underserved areas ',
  'mission'),
 ('we strive to redefine urban mobility by developing electric and shared transportation solutions that reduce congestion and carbon emissions ',
  'mission'),
 ('our mission is to empower individuals to lead healthier lives by providing personalized fitness and wellness solutions ',
  'mission'),
 ('we are on a mission to revolutionize the real estate industry through technology driven solutions that streamline property transactions ',
  'mission'),
 ('our mission is to bridge the digital divide by providing internet connectivity and digital literacy programs to underserved communities ',
  'mission'),
 ('we are committed to advancing renewable energy adoption by developing innovative solar and wind power solutions ',
  'mission'),
 ('our mission is to empower small businesses with cutting edge technology and strategic support to fuel their growth and success ',
  'mission'),
 ('we are on a mission to revolutionize the way people communicate and connect through innovative messaging and collaboration platforms ',
  'mission'),
 ('our mission is to make quality healthcare accessible to all by leveraging telemedicine and digital health solutions ',
  'mission'),
 ('we are dedicated to transforming the agriculture industry through sustainable farming practices and advanced agricultural technologies ',
  'mission'),
 ('our mission is to disrupt the traditional banking industry by providing secure and user friendly digital banking solutions ',
  'mission'),
 ('we are committed to improving mental health and well being by offering accessible and personalized mental health services ',
  'mission'),
 ('our mission is to empower individuals with disabilities by developing assistive technologies that enhance their independence and quality of life ',
  'mission'),
 ('we are on a mission to revolutionize the way people travel by creating innovative transportation solutions that are efficient and environmentally friendly ',
  'mission'),
 ('our mission is to foster creativity and innovation by providing a platform for artists and creators to showcase and monetize their work ',
  'mission'),
 ('we are dedicated to advancing sustainable fashion by promoting ethical practices and offering eco friendly clothing alternatives ',
  'mission'),
 ('our mission is to empower the next generation of leaders by providing comprehensive education and leadership development programs ',
  'mission'),
 ('we are committed to tackling climate change by developing and implementing sustainable energy solutions on a global scale ',
  'mission'),
 ('our mission is to bridge the digital skills gap by offering accessible and comprehensive online learning programs for individuals of all backgrounds ',
  'mission'),
 ('we are on a mission to transform the food industry by promoting healthy and sustainable food choices through innovative products and services ',
  'mission'),
 ('our mission is to revolutionize the healthcare experience by leveraging technology to deliver personalized and patient centric care ',
  'mission'),
 ('we are dedicated to empowering women in tech by providing mentorship networking opportunities and resources for career advancement ',
  'mission'),
 ('our mission is to promote environmental conservation by raising awareness and implementing conservation initiatives worldwide ',
  'mission'),
 ('we are committed to advancing artificial intelligence and machine learning technologies to drive innovation across industries ',
  'mission'),
 ('our mission is to empower underprivileged communities by providing access to education healthcare and economic opportunities ',
  'mission'),
 ('we are on a mission to transform the way people learn by developing interactive and immersive educational platforms and tools ',
  'mission'),
 ('our mission is to revolutionize the fitness industry by combining technology and fitness to deliver personalized and engaging workout experiences ',
  'mission'),
 ('we are dedicated to promoting social impact by supporting social entrepreneurs and fostering sustainable business models ',
  'mission'),
 ('our mission is to empower individuals with financial literacy and independence through innovative financial education programs ',
  'mission'),
 ('we are committed to revolutionizing the entertainment industry by creating captivating and immersive storytelling experiences ',
  'mission'),
 ('our mission is to empower marginalized communities by providing access to technology education and economic opportunities ',
  'mission'),
 ('we are on a mission to transform the way people experience art and culture by leveraging digital platforms and virtual reality ',
  'mission'),
 ('our mission is to improve accessibility and inclusivity in the design and development of products and services ',
  'mission'),
 ('we are dedicated to promoting sustainable tourism by offering eco friendly travel experiences and supporting local communities ',
  'mission'),
 ('our mission is to revolutionize the healthcare supply chain by leveraging blockchain technology for enhanced transparency and efficiency ',
  'mission'),
 ('we are committed to fostering innovation in renewable energy solutions to accelerate the transition to a sustainable and clean energy future ',
  'mission'),
 ('our mission is to empower entrepreneurs and startups by providing comprehensive resources mentorship and access to funding ',
  'mission'),
 ('we are on a mission to eradicate poverty and create economic opportunities for disadvantaged communities ',
  'mission'),
 ('our mission is to revolutionize the beauty industry by offering inclusive and sustainable beauty products ',
  'mission'),
 ('we are dedicated to improving accessibility in technology by developing assistive devices and inclusive software solutions ',
  'mission'),
 ('our mission is to empower individuals with disabilities by promoting accessibility and inclusion in all aspects of life ',
  'mission'),
 ('we are committed to promoting gender equality and empowering women in the workplace ',
  'mission'),
 ('our mission is to revolutionize the healthcare system by leveraging artificial intelligence and data analytics for personalized medicine ',
  'mission'),
 ('we are on a mission to transform the agriculture industry by promoting organic farming and sustainable agricultural practices ',
  'mission'),
 ('our mission is to create a more connected world by developing innovative communication technologies ',
  'mission'),
 ('we are dedicated to fostering innovation and entrepreneurship by providing startup incubation and accelerator programs ',
  'mission'),
 ('our mission is to promote sustainable living and environmental stewardship through eco friendly products and education ',
  'mission'),
 ('we are committed to advancing renewable energy solutions to combat climate change and reduce reliance on fossil fuels ',
  'mission'),
 ('our mission is to empower individuals with digital skills for the digital age through accessible and affordable training programs ',
  'mission'),
 ('we are on a mission to revolutionize the e commerce industry by creating a seamless and personalized online shopping experience ',
  'mission'),
 ('our mission is to improve global healthcare outcomes by leveraging technology and data driven solutions ',
  'mission'),
 ('we are dedicated to promoting diversity and inclusion in the workplace by fostering a culture of belonging ',
  'mission'),
 ('our mission is to empower small businesses and entrepreneurs by providing them with tools and resources for success ',
  'mission'),
 ('we are committed to promoting sustainable agriculture and food security through innovative farming practices ',
  'mission'),
 ('our mission is to revolutionize the transportation industry by developing autonomous and electric vehicles ',
  'mission'),
 ('we are on a mission to eliminate food waste and hunger through innovative food redistribution solutions ',
  'mission'),
 ('our mission is to empower individuals to lead healthy and fulfilling lives through fitness and wellness programs ',
  'mission'),
 ('we are dedicated to promoting social justice and equality through advocacy and community engagement ',
  'mission'),
 ('our mission is to advance scientific research and discovery for the benefit of humanity ',
  'mission'),
 ('we are committed to improving access to quality education for underserved communities around the world ',
  'mission'),
 ('our mission is to revolutionize the gaming industry by creating immersive and interactive gaming experiences ',
  'mission'),
 ('we are on a mission to democratize access to financial services and empower individuals to achieve financial freedom ',
  'mission'),
 ('our mission is to promote sustainable fashion by offering eco friendly and ethically sourced clothing options ',
  'mission'),
 ('we are dedicated to promoting arts and culture by supporting artists and preserving cultural heritage ',
  'mission'),
 ('our mission is to empower individuals with disabilities to live independent and fulfilling lives through assistive technologies ',
  'mission'),
 ('we are committed to promoting ethical and responsible business practices in all aspects of our operations ',
  'mission'),
 ('our mission is to foster innovation and entrepreneurship in underserved communities to drive economic growth ',
  'mission'),
 ('we are on a mission to transform the real estate industry by leveraging technology for seamless property transactions ',
  'mission'),
 ('our mission is to empower youth with leadership and life skills for personal and professional success ',
  'mission')]

# Split the examples into inputs (text) and labels (intents)
inputs = [example[0] for example in examples]
labels = [example[1] for example in examples]

# Preprocess the inputs
vectorizer = CountVectorizer()
features = vectorizer.fit_transform(inputs)

def preprocess_text(text):
    # Remove special characters and extra whitespaces
    text = re.sub(r"[^a-zA-Z0-9]", " ", text)
    text = re.sub(r"\s+", " ", text)
    # Convert to lowercase
    text = text.lower()
    return text

st.title("Audio Recorder")
audio = audiorecorder("Click to record", "Recording...")

if len(audio) > 0:
    # To play audio in frontend:
    st.audio(audio.tobytes())

    # To save audio to a file:
    wav_file = open("audio.mp3", "wb")
    wav_file.write(audio.tobytes())
    wav_file.close()  # Close the file after writing

    # Load the audio data from the saved file
    audio_data = whisper.load_audio("audio.mp3")

    # Transcribe the audio
    model_w = whisper.load_model("base")
    result = model_w.transcribe(audio_data, fp16=False)
    text = result["text"]

    model = pickle.load(open('model.pkl', 'rb'))

    # Split the test paragraph into sentences
    sentences = re.split(r'\.\s*', text)

    # Create a dictionary to store the sentences for each intent
    intent_sentences = {}
    
    # Iterate over each sentence and predict the intent
    with open('output.txt', 'a') as f:
        for sentence in sentences:
            # Remove sentences with less than 6 words
            if len(sentence.split()) < 6:
                continue
    
            preprocessed_sentence = preprocess_text(sentence)
            input_feature = vectorizer.transform([preprocessed_sentence])
            predicted_intent = model.predict(input_feature)[0]
    
            # Add the sentence to the corresponding intent in the dictionary
            if predicted_intent not in intent_sentences:
                intent_sentences[predicted_intent] = []
            intent_sentences[predicted_intent].append(sentence)
            
            # Write the output to the file
            f.write("Line: " + sentence + "\n")
            f.write("Predicted Intent: " + predicted_intent + "\n")

    # Display each intent and its sentences separately
    for intent, sentences in intent_sentences.items():
        # Create a DataFrame for the intent
        df = pd.DataFrame(sentences, columns=['Sentence'])
    
        # Display the intent and its sentences as a table using Streamlit
        st.subheader(f"Intent: {intent}")
        st.table(df)

    with open('output.txt','r') as f:
       st.download_button('Download TXT', f) 
      
    # Read the content of the output.txt file
    with open('output.txt', 'r') as f:
        output_content = f.read()
        os.remove("output.txt")
      
    # Check if the predicted intent is "Investment"
    if 'Predicted Intent: Investment' in output_content:
        # Load the Investor Excel file
        data = pd.read_excel('Investors.xlsx')
    
        # Save the Excel file to a BytesIO object
        excel_file = BytesIO()
        with pd.ExcelWriter(excel_file, engine='xlsxwriter') as writer:
            data.to_excel(writer, index=False, sheet_name='Investor Info')
        excel_file.seek(0)
    
        # Provide download button for the Investor Excel file
        st.download_button('Download Investor Info', excel_file, file_name='Investors.xlsx', mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
      
    






